apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-storage-pvc01               # Pod생성할 때 사용하는 pvc의 이름
  labels:
    name: provision
spec:
  storageClassName: nfs-storageclass  # storageClassName 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-storage-pvc02               # Pod생성할 때 사용하는 pvc의 이름
  labels:
    name: provision
spec:
  storageClassName: nfs-storageclass  # storageClassName 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi