apiVersion: v1
kind: Pod
metadata:
  name: nfs-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nfsvol
      mountPath: /usr/share/nginx/html
  volumes:
  - name : nfsvol
    nfs:                                # volume type 정의 emptyDir, hostPath등 가능
      path: /nfsVolume                  # nfs의 file share name
      server: 172.27.192.130            # nfs ip  # 172.27.192.130:/nfsVolume 의 의미임
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-nginx-check
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nfsvol
      mountPath: /usr/share/nginx/html
  volumes:
  - name : nfsvol
    nfs:                              
      path: /nfsVolume                
      server: 172.27.192.130          