apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs               # pvc의 이름으로 pod에서 볼륨을 요청할때 사용
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi            # 실제 pv에 요청하는 용량