apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.14.2
          ports:
            - containerPort: 80
    