apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80   # container 안의 앱의 port로 설정해야 함
          
