apiVersion: apps/v1       
kind: Deployment
metadata:
  name: deployment-sample
  # kubernetes change-cause 기입
  annotations:
    kubernetes.io/change-cause: "update deployment image nginx:1.22.1"
spec:
  # replicas를 3 -> 2 로 변경
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-container
          # image를 1.14.2 -> 1.22.1 로 변경
          image: nginx:1.22.1
          ports:
            - containerPort: 80
    