apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    name: nginx
spec:
  volumes:
    - name: pw                                    # container 내부에서 참조할 name
      secret:                                     # 외부에 생성된 secret 참조 
        secretName: db-config                     # secretName에 모든 secret 정보 담기
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pw                                # volumes - name 의 값과 맞춰주어야함
          mountPath: /var/share/nginx/html
      
