apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-sample
  labels:
    app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      nodeSelector:        # nodeSelector label key:value 입력하여 node선택
        node: development
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.13-1
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers