apiVersion: apps/v1                                         # apiVersion
kind: ReplicaSet
metadata:
  name: replica-sample
spec:
  replicas: 3                   
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo          
    spec:
      containers:
        - name: app-container
          image: nginx
       